Marker pixel info
pal-robotics/aruco_ros pull request #30
Opened 2017-04-09 20:21 UTC by JakeBrawer

The Marker msg type now contains data relating to pixel coordinates of a marker's corners and center.

2017-04-10 11:02 UTC, bmagyar reviewed
Please sort out the conflict with the package.xml as well.

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/launch/baxter_marker_publisher.launch
> +<launch>
This file should not be here

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/scripts/ik_service_client+mover.py
> +#!/usr/bin/env python
This file should not be here

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +string int_to_string( const int a )
Please handle this in the minimal invasive way.
This seems like a good alternative to adding a new function: http://www.boost.org/doc/libs/1_55_0/doc/html/boost_lexical_cast/examples.html

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +    //image_sub_ = it_.subscribe("/cameras/left_hand_camera/image", 1, &ArucoMarkerPublisher::image_callback, this);
Please remove this line.

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +      //sensor_msgs::CameraInfoConstPtr msg = ros::topic::waitForMessage<sensor_msgs::CameraInfo>("/cameras/left_hand_camera/camera_info", nh_);//, 10.0);
Please remove this line.

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +              // printf("%s %s\n", reference_frame_.c_str(), ("/marker_"+int_to_string(marker_i.id)).c_str());
Please remove this line.

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +  ROS_INFO("Starting ARUCO Marker Publisher");
Please remove this line.

2017-04-10 11:02 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +          if (markers_.size()>0)
This is just for debugging. This information is being published. Please remove it.

2017-07-13 14:39 UTC, bmagyar requested changes
I've added a few new ones but most of the old requested changes still remain.

2017-07-13 14:39 UTC, bmagyar commented on aruco/src/aruco/marker.cpp
> +    cout<<"Marker "<<(*this)<<endl;
This needs to be removed

2017-07-13 14:39 UTC, bmagyar commented on aruco_ros/CMakeLists.txt
> +add_library(aruco_ros
The library name could be misleading. I think aruco_ros_utils would be better

2017-07-13 15:05 UTC, jdlangs commented
There doesn't seem to be any way to deduce the added message fields are in pixels without reading the code. Ideally, it should be obvious from the names of the fields themselves.

2017-07-13 15:06 UTC, jdlangs commented
Also, am I just missing something or does the new `center` message field never get populated?

2017-07-13 15:08 UTC, jdlangs commented on aruco_ros/src/marker_publish.cpp
> +string int_to_string( const int a )
If it's ok to add the C++11 build flag to `CMakeLists.txt`, `std::to_string` would be the way to go.

2017-07-13 15:16 UTC, bmagyar commented
Thanks @jdlangs for the extra notes, the center could be removed as it's trivial to compute it from the corners.

2017-07-13 15:17 UTC, bmagyar commented on aruco_ros/src/marker_publish.cpp
> +string int_to_string( const int a )
:+1:

2017-07-13 15:43 UTC, JakeBrawer commented
Hello all, thank you for your timely and trenchant comments. I actually meant to open this pull request on our own fork of this repo, but obviously failed to do so as I am a noob apparently :^).  Unless you actually find any of this useful, do you think you can terminate this PR (or tell me how to do it!). Thanks again, and sorry for the confusion.

2017-07-17 22:49 UTC, closed without merging